baseURL = 'https://armanwu.github.io/'
languageCode = 'en-us'
title = 'Arman Wu'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menus]
  [[menus.main]]
    name = "Essays"
    pageRef = "/posts"
    weight = 10

  [[menus.main]]
    name = "Projects"
    pageRef = "/projects"
    weight = 20

  [[menus.main]]
    name = "Publications"
    pageRef = "/publications"
    weight = 30

   [[menus.main]]
    name = "About"
    pageRef = "/about"
    weight = 40
  
  [services]
  [services.googleAnalytics]
    ID = 'G-96RWB4ME5V'
  
  [outputs]
  home = ["HTML", "RSS", "JSON"]
